# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dateofbirth',
            field=models.DateTimeField(null=True),
        ),
    ]
